### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by davelab6** [coldbreeze16/Lekhani#1]
Please add a LICENSE file with a libre license; I recommend the SIL Open Font License with no Reserved Font Name

**Comment by coldbreeze16** [comment]
Done. I've added the BSD license. Might change to SIL once the font is complete.

**Comment by davelab6** [comment]
If anyone contributes to the repo then changing  the license gets a bit
complicated

Also if you would like to make the font easily available via Google Fonts,
the ofl is ideal :)

**Comment by coldbreeze16** [comment]
Fine then, I've changed to OFL. I originally intended to use it but I find it tad bit restrictive.

**Comment by davelab6** [comment]
Thanks! I think the OFL has problems, but they are all minor; overall I think it strikes a good balance between the needs of the software freedom movement community and the (font) design community, and by not using an RFN then it has no authoring burdens and is really simple to derive or reuse, like BSD :)
